#!/bin/bash

# ==============================================================================
# Універсальний скрипт для установки та налаштування драйвера Realtek RTL8125
# Запускається двічі: до і після перезавантаження.
# ==============================================================================

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Перевірка прав root
if [[ $EUID -ne 0 ]]; then
   echo -e "${YELLOW}Помилка: Запустіть скрипт з правами root (sudo).${NC}"
   exit 1
fi

# --- ОСНОВНА ЛОГІКА ---

# Перевіряємо, чи драйвер r8125 вже завантажено в ядро
if lsmod | grep -q r8125; then
    # --- ЕТАП 2: Драйвер вже встановлено, налаштовуємо мережу ---
    echo -e "${GREEN}Драйвер r8125 знайдено. Починаємо налаштування мережі...${NC}"

    # Автоматично знаходимо назву інтерфейсу Realtek RTL8125
    INTERFACE_NAME=""
    # Знаходимо PCI-адресу пристрою, для якого використовується драйвер r8125
    PCI_ADDRESS=$(lspci -k | grep -A 2 r8125 | head -n 1 | awk '{print $1}')
    if [ -n "$PCI_ADDRESS" ]; then
        # Знаходимо назву мережевого інтерфейсу за його PCI-адресою
        INTERFACE_NAME=$(ls /sys/bus/pci/devices/*${PCI_ADDRESS}/net/ | head -n 1)
    fi

    if [ -z "$INTERFACE_NAME" ]; then
        echo -e "${YELLOW}Не вдалося автоматично знайти назву мережевої карти. Будь ласка, налаштуйте /etc/network/interfaces вручну.${NC}"
        exit 1
    fi

    echo "Знайдено мережеву карту: ${INTERFACE_NAME}"

    # Запитуємо у користувача мережеві налаштування
    read -p "Введіть статичну IP-адресу для сервера (напр., 192.168.1.111/24): " STATIC_IP
    read -p "Введіть IP-адресу вашого шлюзу (напр., 192.168.1.1): " GATEWAY

    echo "Створюємо резервну копію /etc/network/interfaces..."
    cp /etc/network/interfaces /etc/network/interfaces.bak_$(date +%F-%T)

    echo "Генеруємо новий файл конфігурації..."
    cat <<EOF > /etc/network/interfaces
# Generated by install.sh script
auto lo
iface lo inet loopback

iface ${INTERFACE_NAME} inet manual

auto vmbr0
iface vmbr0 inet static
    address ${STATIC_IP}
    gateway ${GATEWAY}
    bridge-ports ${INTERFACE_NAME}
    bridge-stp off
    bridge-fd 0
EOF

    echo "Застосовуємо нові налаштування мережі..."
    systemctl restart networking.service

    echo -e "\n${GREEN}### ЗАВЕРШЕНО! ###${NC}"
    echo "Мережу налаштовано. Ваш сервер тепер доступний за адресою: ${STATIC_IP}"
    echo "Поточна конфігурація збережена у /etc/network/interfaces."

else
    # --- ЕТАП 1: Драйвер ще не встановлено ---
    echo -e "${GREEN}Драйвер r8125 не знайдено. Починаємо процес установки...${NC}"
    
    echo -e "\n${GREEN}Налаштування репозиторіїв Proxmox...${NC}"
    sed -i 's/^deb/# deb/' /etc/apt/sources.list.d/pve-enterprise.list
    if [ -f /etc/apt/sources.list.d/ceph.list ]; then
        sed -i 's/^deb/# deb/' /etc/apt/sources.list.d/ceph.list
    fi
    echo "deb http://download.proxox.com/debian/pve bookworm pve-no-subscription" > /etc/apt/sources.list.d/pve-no-subscription.list
    apt update > /dev/null 2>&1
    
    echo -e "\n${GREEN}Встановлення залежностей...${NC}"
    apt install -y pve-headers-$(uname -r) dkms
    
    echo -e "\n${GREEN}Встановлення драйвера r8125 через DKMS...${NC}"
    if [ ! -f ./dkms-install.sh ]; then
        echo -e "${YELLOW}Помилка: Скрипт dkms-install.sh не знайдено в поточному каталозі!${NC}"
        exit 1
    fi
    ./dkms-install.sh
    
    echo -e "\n${GREEN}### ЕТАП 1 ЗАВЕРШЕНО! ###${NC}"
    echo -e "${YELLOW}Драйвер встановлено. Тепер НЕОБХІДНО перезавантажити сервер.${NC}"
    echo "Після перезавантаження запустіть цей самий скрипт './install.sh' ще раз, щоб налаштувати мережу."
    read -p "Перезавантажити зараз? (y/n): " reboot_choice

    if [[ "$reboot_choice" == "y" || "$reboot_choice" == "Y" ]]; then
        echo "Перезавантаження..."
        reboot
    fi
fi